<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var string
     */
    private $accessCode;

    /**
     * @var \DateTime
     */
    private $activatedDate;


    /**
     * Set AccessCode
     *
     * @param string $accessCode
     * @return User
     */
    public function setAccessCode($accessCode)
    {
        $this->accessCode = $accessCode;

        return $this;
    }

    /**
     * Get AccessCode
     *
     * @return string 
     */
    public function getAccessCode()
    {
        return $this->accessCode;
    }

    /**
     * Set activatedDate
     *
     * @param \DateTime $activatedDate
     * @return User
     */
    public function setActivatedDate($activatedDate)
    {
        $this->activatedDate = $activatedDate;

        return $this;
    }

    /**
     * Get activatedDate
     *
     * @return \DateTime 
     */
    public function getActivatedDate()
    {
        return $this->activatedDate;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $flights;


    /**
     * Add flights
     *
     * @param \AppBundle\Entity\Flight $flights
     * @return User
     */
    public function addFlight(\AppBundle\Entity\Flight $flights)
    {
        $this->flights[] = $flights;

        return $this;
    }

    /**
     * Remove flights
     *
     * @param \AppBundle\Entity\Flight $flights
     */
    public function removeFlight(\AppBundle\Entity\Flight $flights)
    {
        $this->flights->removeElement($flights);
    }

    /**
     * Get flights
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFlights()
    {
        return $this->flights;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $travelers;


    /**
     * Add travelers
     *
     * @param \AppBundle\Entity\Traveler $travelers
     * @return User
     */
    public function addTraveler(\AppBundle\Entity\Traveler $travelers)
    {
        $this->travelers[] = $travelers;

        return $this;
    }

    /**
     * Remove travelers
     *
     * @param \AppBundle\Entity\Traveler $travelers
     */
    public function removeTraveler(\AppBundle\Entity\Traveler $travelers)
    {
        $this->travelers->removeElement($travelers);
    }

    /**
     * Get travelers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTravelers()
    {
        return $this->travelers;
    }
 
    /**
     * @var \Application\Sonata\MediaBundle\Entity\Media
     */
    private $profilePicture;


    /**
     * Set profilePicture
     *
     * @param \Application\Sonata\MediaBundle\Entity\Media $profilePicture
     * @return User
     */
    public function setProfilePicture(\Application\Sonata\MediaBundle\Entity\Media $profilePicture = null)
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    /**
     * Get profilePicture
     *
     * @return \Application\Sonata\MediaBundle\Entity\Media 
     */
    public function getProfilePicture()
    {
        return $this->profilePicture;
    }
    /**
     * @var string
     */
    private $telephoneNumber;


    /**
     * Set telephoneNumber
     *
     * @param string $telephoneNumber
     * @return User
     */
    public function setTelephoneNumber($telephoneNumber)
    {
        $this->telephoneNumber = $telephoneNumber;

        return $this;
    }

    /**
     * Get telephoneNumber
     *
     * @return string 
     */
    public function getTelephoneNumber()
    {
        return $this->telephoneNumber;
    }
}
